// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCan6_P2CRv3mDCRXPleoYeOb-YzbE49g',
    appId: '1:797297990117:web:2de4eca2d6ac74c17db70c',
    messagingSenderId: '797297990117',
    projectId: 'softwarenomad-80e70',
    authDomain: 'softwarenomad-80e70.firebaseapp.com',
    storageBucket: 'softwarenomad-80e70.appspot.com',
    measurementId: 'G-4BXGYWT47W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4SQO-qnIkM5bJatwRhvi8_G1KkH13bwY',
    appId: '1:797297990117:android:0362435e7e2249157db70c',
    messagingSenderId: '797297990117',
    projectId: 'softwarenomad-80e70',
    storageBucket: 'softwarenomad-80e70.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF62Q2kHnHDNhPexb_8QoajlcV2SI4xuk',
    appId: '1:797297990117:ios:df09aaa3ed715c627db70c',
    messagingSenderId: '797297990117',
    projectId: 'softwarenomad-80e70',
    storageBucket: 'softwarenomad-80e70.appspot.com',
    iosBundleId: 'com.example.softwareengineering',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF62Q2kHnHDNhPexb_8QoajlcV2SI4xuk',
    appId: '1:797297990117:ios:df09aaa3ed715c627db70c',
    messagingSenderId: '797297990117',
    projectId: 'softwarenomad-80e70',
    storageBucket: 'softwarenomad-80e70.appspot.com',
    iosBundleId: 'com.example.softwareengineering',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCan6_P2CRv3mDCRXPleoYeOb-YzbE49g',
    appId: '1:797297990117:web:31ac70caa5dd05ec7db70c',
    messagingSenderId: '797297990117',
    projectId: 'softwarenomad-80e70',
    authDomain: 'softwarenomad-80e70.firebaseapp.com',
    storageBucket: 'softwarenomad-80e70.appspot.com',
    measurementId: 'G-CKVZ75P3DT',
  );
}
